# Generated by Django 6.0.7 on 2026-08-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_cake_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='image',
        ),
    ]
