# Generated by Django 6.0.7 on 2026-08-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_category_cake_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='cakes', to='cakes.ingredients'),
        ),
    ]
